<a href="https://colab.research.google.com/github/klein-Esperanza/Deep-Learning-Study/blob/main/DeepLearning_LIMU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.cuda.is_available()) # True表示GPU可用
print(torch.cuda.get_device_name(0)) # 查看GPU型号

True
Tesla T4


In [ ]:
!pip install torch torchvision torchaudio
!pip install d2l

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 2.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 115.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 90.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 55.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 13.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 4.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 96.2 MB/s eta 0:00:00
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitli

In [ ]:
!pip install torch torchvision torchaudio
!pip install d2l

In [ ]:
!git clone https://github.com/d2l-ai/d2l-zh.git

Cloning into 'd2l-zh'...
remote: Enumerating objects: 24068, done.
remote: Total 24068 (delta 0), reused 0 (delta 0), pack-reused 24068 (from 1)
Receiving objects: 100% (24068/24068), 309.44 MiB | 16.88 MiB/s, done.
Resolving deltas: 100% (16835/16835), done.


In [ ]:
%cd d2l-zh

[Errno 2] No such file or directory: 'd2l-zh'
/content/d2l-zh


In [ ]:
!git clone https://github.com/d2l-ai/d2l-zh.git

Cloning into 'd2l-zh'...
remote: Enumerating objects: 24068, done.
remote: Total 24068 (delta 0), reused 0 (delta 0), pack-reused 24068 (from 1)
Receiving objects: 100% (24068/24068), 309.44 MiB | 16.73 MiB/s, done.
Resolving deltas: 100% (16832/16832), done.


In [ ]:
%cd d2l-zh

/content/d2l-zh/d2l-zh


In [ ]:
%cd /content/d2l-zh

/content/d2l-zh


In [ ]:
!ls

chapter_appendix-tools-for-deep-learning	  chapter_recurrent-neural-networks
chapter_attention-mechanisms			  chapter_references
chapter_computational-performance		  ci
chapter_computer-vision				  config.ini
chapter_convolutional-modern			  contrib
chapter_convolutional-neural-networks		  d2l
chapter_deep-learning-computation		  d2l.bib
chapter_installation				  d2l-zh
chapter_introduction				  graffle
chapter_linear-networks				  img
chapter_multilayer-perceptrons			  index.md
chapter_natural-language-processing-applications  INFO.md
chapter_natural-language-processing-pretraining   LICENSE
chapter_notation				  README.md
chapter_optimization				  setup.py
chapter_preface					  static
chapter_preliminaries				  STYLE_GUIDE.md
chapter_recurrent-modern			  TERMINOLOGY.md


In [ ]:
import torch
x = torch.rand(2, 3)
print(x)


tensor([[0.6262, 0.7024, 0.7000],
        [0.0886, 0.6820, 0.2885]])


In [ ]:
from d2l import torch as d2l
d2l.use_svg_display()


In [ ]:
# 挂载Google Drive,持久化数据
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


# 数据操作

In [ ]:
import torch

In [ ]:
x = torch.arange(12) # 包含0到11的1D张量（向量）
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
x.shape # 显示张量x的形状 显示x为长度12的一维张量

torch.Size([12])

In [ ]:
x.numel() # 显示张量中元素的总数

12

In [ ]:
x.reshape(3, 4) # 改变张量形状而不改变元素数量和元素值

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
torch.zeros((2,3,4)) #创建全0函数，形状2,3,4元素全0

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
torch.tensor([[[2,1,4,3],[1,2,3,4],[4,3,2,1]]]).shape # 通过提供包含数值的Python列表(或嵌套列表)来为所需张量中的每个元素赋予确定值

torch.Size([1, 3, 4])

In [ ]:
# 常见的标准算术运算符（+、-、*、/ 和 **）都可以被升级为按元素运算
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [ ]:
# 我们也可以把多个张量 连结（concatenate） 在一起
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)
# dimension=0 按行拼接（上下叠加） dimension=1 按列拼接（左右并排）

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [ ]:
# 通过逻辑运算符构建二元张量
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
# 对张量中所有元素进行求和会产生一个只有一个元素的张量
X.sum()

tensor(66.)

**注意此处广播机制容易出错**:

In [ ]:
# 即使形状不同，我们仍然可以通过调用 广播机制（broadcasting mechanism）来执行元素操作
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [ ]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [ ]:
# 可以用[-1]选择最后一个元素，可以用[1:3]选择第二个和第三个元素
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [ ]:
# 通过指定索引来将元素写入矩阵
X[1,2] = 9
X


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [ ]:
# 为多个元素赋值相同的值，我们只需要索引所有元素，然后为它们赋值
X[0:2,:] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [ ]:
# 运行一些操作可能会导致为新结果分配内存
before = id(Y)
Y = Y + X
id(Y) == before

False

In [ ]:
# 执行原地操作
Z = torch.zeros_like(Y)
print('id(Z):',id(Z))
Z[:] = X + Y
print('id(Z):',id(Z))

id(Z): 138048525727216
id(Z): 138048525727216


In [ ]:
# 如果在后续计算中没有重复使用X，我们也可以使用 X[:] = X + Y 或 X += Y 来减少内存的消耗
before = id(X)
X += Y
id(X) == before

True

In [ ]:
# 转换为NumPy张量
# NumPy——Python中最基础的多元数组框架
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [ ]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

# 数据预处理

In [ ]:
# 创建一个人工数据集，并存储在csv（逗号分隔值）文件
import os

os.makedirs(os.path.join('..','data'), exist_ok=True)
data_file = os.path.join('..','data','house_tiny.csv')
with open(data_file, 'w') as f:
  f.write('NumRooms,Alley,Price\n') # 列名
  f.write('NA,Pave,127500\n') # 每行表示一个数据样本
  f.write('2,NA,106000\n')
  f.write('4,NA,178100\n')
  f.write('NA,NA,140000\n')

In [ ]:
# 从创建的csv文件中加载原始数据集
import pandas as pd

data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [ ]:
# 为了处理缺失的数据，典型的方法包括 插值 和 删除，这里，我们将考虑插值
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean()) # Alley为字符串，非数值序列，代码默认跳过，但某些pandas环境下会报错
print(inputs)

TypeError: can only concatenate str (not "int") to str

In [ ]:
# 调整后代码
# 先将输入分为数值列和非数值列
inputs = data.iloc[:, 0:2].copy()
numeric_cols = inputs.select_dtypes(include='number').columns
inputs[numeric_cols] = inputs[numeric_cols].fillna(inputs[numeric_cols].mean())
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [ ]:
# 对于inputs中的类别值或离散值，我们将"NaN"视为一个类别
inputs = pd.get_dummies(inputs, dummy_na=True)# 把类别变量（比如字符串）转换为 独热编码（One-Hot Encoding）
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True


In [ ]:
# 更改为int显示
inputs = pd.get_dummies(inputs, dummy_na=True).astype(int)
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0         3           1          0
1         2           0          1
2         4           0          1
3         3           0          1


In [ ]:
# 现在inputs和outputs中的所有条目都是数值类型，它们可以转换为张量格式
import torch

x, y = torch.tensor(inputs.values), torch.tensor(outputs.values)
x, y

(tensor([[3, 1, 0],
         [2, 0, 1],
         [4, 0, 1],
         [3, 0, 1]]),
 tensor([127500, 106000, 178100, 140000]))

In [ ]:
# 更改为浮点数
x = torch.tensor(inputs.values, dtype=torch.float32)
y = torch.tensor(outputs.values, dtype=torch.float32)
x, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]]),
 tensor([127500., 106000., 178100., 140000.]))