<a href="https://colab.research.google.com/github/klein-Esperanza/Deep-Learning-Study/blob/main/Numpy/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.创建数组

In [1]:
import numpy as np

In [2]:
# 创建一维数组
a1 = np.array([1,2,3])
print("一维数组：", a1)

一维数组： [1 2 3]


In [4]:
# 创建二维数组（2x3 的零矩阵）
a2 = np.zeros((2, 3))
print("零矩阵：\n", a2)

零矩阵：
 [[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
# 创建二维数组（3x3 的单位矩阵）
a3 = np.ones((3, 3))
print("单位矩阵：\n", a3)

单位矩阵：
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
# 创建一个从0到10（不包括10），步长为2的数组
# 步长：每次加2 -- 从0开始，每次加2，直到小于10为止
a4 = np.arange(0, 10, 2) # 创建一个等差数列 起始值包含，终止值不包含 [start, end) 左闭右开区间
print("步长为2的数组：", a4)

步长为2的数组： [0 2 4 6 8]


In [8]:
 # 创建一个包含5个数的等间距数组
 a5 = np.linspace(0, 1, 5)
 print("等间距数组：", a5)

等间距数组： [0.   0.25 0.5  0.75 1.  ]


# 2.数组操作

In [12]:
# reshape:改变数组形状
a = np.arange(12) # 创建一维数组
print(a.shape) # (12,)这个,是因为在Numpy里，数组的shape永远是一个“元组（tuple）" , 强调是一个只有一个元素的元组而非数字12

b = a.reshape(3, 4) # 变成3行4列的矩阵
print(b)
print(b.shape)

(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [13]:
# transpose(或.T):转置
c = b.T # 转置，行列互换
print(c)
print(c.shape)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
(4, 3)


In [15]:
# astype:改变数据类型
d = np.array([1.2, 3.4, 5.6])
print(d.dtype)

e = d.astype(np.int32) # 转成整数
print(e)
print(e.dtype)

float64
[1 3 5]
int32


In [19]:
# copy:深拷贝 vs 浅拷贝
f = np.array([1, 2, 3])

h = f.copy() # 深拷贝
h[0] = 999
print(f) # f不变

g = f # 浅拷贝
g[0] = 100
print(f) # f变化



[1 2 3]
[100   2   3]


In [23]:
# flatten:降维成一维数组
i = np.array([[1, 2, 3], [4, 5, 6]])
j = i.flatten()
print(j)


[1 2 3 4 5 6]


# 3.索引与切片

# 4.广播机制

# 5.数学统计

# 6.矩阵运算

# 7.随机数生成